base: /
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=19'
languages:
  -
    title: Deutsch
    enabled: true
    locale: de_DE
    hreflang: de-DE
    base: /
    websiteTitle: ''
    navigationTitle: ''
    flag: de
    languageId: 0
rootPageId: 1
websiteTitle: 'Liszt-Portal v12'
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /
    index: ''
    map:
      /: 0
      site.webmanifest: 3478304621
